// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectGSMAUI.Api.Data;

#nullable disable

namespace ProjectGSMAUI.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.ChiTietCombo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietCombos");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("GheMaGhe")
                        .HasColumnType("char(10)");

                    b.Property<int?>("Gia")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaChiTietHoaDon")
                        .HasName("PK__ChiTietH__CFF2C426609D1D0B");

                    b.HasIndex("GheMaGhe");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaVe");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaNhap")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .IsFixedLength();

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Coupon__3214EC27700E1307");

                    b.HasIndex("MaGiamGia");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaGiamGia = 1,
                            MaNhap = "COUPON001",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            MaGiamGia = 1,
                            MaNhap = "COUPON002",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            MaGiamGia = 1,
                            MaNhap = "COUPON003",
                            TrangThai = false
                        },
                        new
                        {
                            Id = 4,
                            MaGiamGia = 1,
                            MaNhap = "COUPON004",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            MaGiamGia = 1,
                            MaNhap = "COUPON005",
                            TrangThai = false
                        },
                        new
                        {
                            Id = 6,
                            MaGiamGia = 1,
                            MaNhap = "COUPON006",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 7,
                            MaGiamGia = 1,
                            MaNhap = "COUPON007",
                            TrangThai = false
                        },
                        new
                        {
                            Id = 8,
                            MaGiamGia = 1,
                            MaNhap = "COUPON008",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 9,
                            MaGiamGia = 1,
                            MaNhap = "COUPON009",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 10,
                            MaGiamGia = 1,
                            MaNhap = "COUPON010",
                            TrangThai = false
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.DatVe", b =>
                {
                    b.Property<int?>("MaDatVe")
                        .HasColumnType("int");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("NgayDat")
                        .HasColumnType("date");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaVe");

                    b.ToTable("DatVe", (string)null);
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Ghe", b =>
                {
                    b.Property<string>("MaGhe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("SoCot")
                        .HasColumnType("int");

                    b.Property<string>("SoHang")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("MaGhe")
                        .HasName("PK__Ghe__3CD3C67B40EF14C7");

                    b.ToTable("Ghe", (string)null);

                    b.HasData(
                        new
                        {
                            MaGhe = "A1",
                            SoCot = 1,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A2",
                            SoCot = 2,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A3",
                            SoCot = 3,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A4",
                            SoCot = 4,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A5",
                            SoCot = 5,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A6",
                            SoCot = 6,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A7",
                            SoCot = 7,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A8",
                            SoCot = 8,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A9",
                            SoCot = 9,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A10",
                            SoCot = 10,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A11",
                            SoCot = 11,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A12",
                            SoCot = 12,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A13",
                            SoCot = 13,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A14",
                            SoCot = 14,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A15",
                            SoCot = 15,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "A16",
                            SoCot = 16,
                            SoHang = "A"
                        },
                        new
                        {
                            MaGhe = "B1",
                            SoCot = 1,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B2",
                            SoCot = 2,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B3",
                            SoCot = 3,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B4",
                            SoCot = 4,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B5",
                            SoCot = 5,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B6",
                            SoCot = 6,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B7",
                            SoCot = 7,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B8",
                            SoCot = 8,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B9",
                            SoCot = 9,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B10",
                            SoCot = 10,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B11",
                            SoCot = 11,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B12",
                            SoCot = 12,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B13",
                            SoCot = 13,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B14",
                            SoCot = 14,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B15",
                            SoCot = 15,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "B16",
                            SoCot = 16,
                            SoHang = "B"
                        },
                        new
                        {
                            MaGhe = "C1",
                            SoCot = 1,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C2",
                            SoCot = 2,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C3",
                            SoCot = 3,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C4",
                            SoCot = 4,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C5",
                            SoCot = 5,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C6",
                            SoCot = 6,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C7",
                            SoCot = 7,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C8",
                            SoCot = 8,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C9",
                            SoCot = 9,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C10",
                            SoCot = 10,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C11",
                            SoCot = 11,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C12",
                            SoCot = 12,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C13",
                            SoCot = 13,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C14",
                            SoCot = 14,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C15",
                            SoCot = 15,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "C16",
                            SoCot = 16,
                            SoHang = "C"
                        },
                        new
                        {
                            MaGhe = "D1",
                            SoCot = 1,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D2",
                            SoCot = 2,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D3",
                            SoCot = 3,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D4",
                            SoCot = 4,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D5",
                            SoCot = 5,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D6",
                            SoCot = 6,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D7",
                            SoCot = 7,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D8",
                            SoCot = 8,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D9",
                            SoCot = 9,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D10",
                            SoCot = 10,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D11",
                            SoCot = 11,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D12",
                            SoCot = 12,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D13",
                            SoCot = 13,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D14",
                            SoCot = 14,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D15",
                            SoCot = 15,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "D16",
                            SoCot = 16,
                            SoHang = "D"
                        },
                        new
                        {
                            MaGhe = "E1",
                            SoCot = 1,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E2",
                            SoCot = 2,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E3",
                            SoCot = 3,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E4",
                            SoCot = 4,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E5",
                            SoCot = 5,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E6",
                            SoCot = 6,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E7",
                            SoCot = 7,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E8",
                            SoCot = 8,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E9",
                            SoCot = 9,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E10",
                            SoCot = 10,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E11",
                            SoCot = 11,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E12",
                            SoCot = 12,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E13",
                            SoCot = 13,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E14",
                            SoCot = 14,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E15",
                            SoCot = 15,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "E16",
                            SoCot = 16,
                            SoHang = "E"
                        },
                        new
                        {
                            MaGhe = "F1",
                            SoCot = 1,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F2",
                            SoCot = 2,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F3",
                            SoCot = 3,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F4",
                            SoCot = 4,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F5",
                            SoCot = 5,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F6",
                            SoCot = 6,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F7",
                            SoCot = 7,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F8",
                            SoCot = 8,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F9",
                            SoCot = 9,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F10",
                            SoCot = 10,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F11",
                            SoCot = 11,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F12",
                            SoCot = 12,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F13",
                            SoCot = 13,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F14",
                            SoCot = 14,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F15",
                            SoCot = 15,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "F16",
                            SoCot = 16,
                            SoHang = "F"
                        },
                        new
                        {
                            MaGhe = "G1",
                            SoCot = 1,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G2",
                            SoCot = 2,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G3",
                            SoCot = 3,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G4",
                            SoCot = 4,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G5",
                            SoCot = 5,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G6",
                            SoCot = 6,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G7",
                            SoCot = 7,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G8",
                            SoCot = 8,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G9",
                            SoCot = 9,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G10",
                            SoCot = 10,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G11",
                            SoCot = 11,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G12",
                            SoCot = 12,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G13",
                            SoCot = 13,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G14",
                            SoCot = 14,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G15",
                            SoCot = 15,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "G16",
                            SoCot = 16,
                            SoHang = "G"
                        },
                        new
                        {
                            MaGhe = "H1",
                            SoCot = 1,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H2",
                            SoCot = 2,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H3",
                            SoCot = 3,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H4",
                            SoCot = 4,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H5",
                            SoCot = 5,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H6",
                            SoCot = 6,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H7",
                            SoCot = 7,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H8",
                            SoCot = 8,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H9",
                            SoCot = 9,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H10",
                            SoCot = 10,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H11",
                            SoCot = 11,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H12",
                            SoCot = 12,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H13",
                            SoCot = 13,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H14",
                            SoCot = 14,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H15",
                            SoCot = 15,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "H16",
                            SoCot = 16,
                            SoHang = "H"
                        },
                        new
                        {
                            MaGhe = "I1",
                            SoCot = 1,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I2",
                            SoCot = 2,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I3",
                            SoCot = 3,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I4",
                            SoCot = 4,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I5",
                            SoCot = 5,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I6",
                            SoCot = 6,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I7",
                            SoCot = 7,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I8",
                            SoCot = 8,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I9",
                            SoCot = 9,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I10",
                            SoCot = 10,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I11",
                            SoCot = 11,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I12",
                            SoCot = 12,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I13",
                            SoCot = 13,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I14",
                            SoCot = 14,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I15",
                            SoCot = 15,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "I16",
                            SoCot = 16,
                            SoHang = "I"
                        },
                        new
                        {
                            MaGhe = "J1",
                            SoCot = 1,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J2",
                            SoCot = 2,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J3",
                            SoCot = 3,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J4",
                            SoCot = 4,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J5",
                            SoCot = 5,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J6",
                            SoCot = 6,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J7",
                            SoCot = 7,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J8",
                            SoCot = 8,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J9",
                            SoCot = 9,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J10",
                            SoCot = 10,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J11",
                            SoCot = 11,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J12",
                            SoCot = 12,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J13",
                            SoCot = 13,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J14",
                            SoCot = 14,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J15",
                            SoCot = 15,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "J16",
                            SoCot = 16,
                            SoHang = "J"
                        },
                        new
                        {
                            MaGhe = "K1",
                            SoCot = 1,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K2",
                            SoCot = 2,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K3",
                            SoCot = 3,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K4",
                            SoCot = 4,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K5",
                            SoCot = 5,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K6",
                            SoCot = 6,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K7",
                            SoCot = 7,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K8",
                            SoCot = 8,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K9",
                            SoCot = 9,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K10",
                            SoCot = 10,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K11",
                            SoCot = 11,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K12",
                            SoCot = 12,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K13",
                            SoCot = 13,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K14",
                            SoCot = 14,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K15",
                            SoCot = 15,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "K16",
                            SoCot = 16,
                            SoHang = "K"
                        },
                        new
                        {
                            MaGhe = "L1",
                            SoCot = 1,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L2",
                            SoCot = 2,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L3",
                            SoCot = 3,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L4",
                            SoCot = 4,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L5",
                            SoCot = 5,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L6",
                            SoCot = 6,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L7",
                            SoCot = 7,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L8",
                            SoCot = 8,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L9",
                            SoCot = 9,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L10",
                            SoCot = 10,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L11",
                            SoCot = 11,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L12",
                            SoCot = 12,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L13",
                            SoCot = 13,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L14",
                            SoCot = 14,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L15",
                            SoCot = 15,
                            SoHang = "L"
                        },
                        new
                        {
                            MaGhe = "L16",
                            SoCot = 16,
                            SoHang = "L"
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.GiamGia", b =>
                {
                    b.Property<int>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<int?>("GiaTri")
                        .HasColumnType("int");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenGiamGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGiamGia")
                        .HasName("PK__GiamGia__EF9458E404C081C8");

                    b.ToTable("GiamGia");

                    b.HasData(
                        new
                        {
                            MaGiamGia = 1,
                            GiaTri = 20,
                            MoTa = "abc",
                            NgayBatDau = new DateOnly(2025, 1, 1),
                            NgayKetThuc = new DateOnly(2024, 6, 30),
                            SoLuong = 10,
                            TenGiamGia = "Khuyến mãi nửa đầu 2025"
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.HinhAnh", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<bool>("Avatar")
                        .HasColumnType("bit");

                    b.Property<string>("ImageData")
                        .HasColumnType("text");

                    b.Property<int?>("Phim")
                        .HasColumnType("int");

                    b.Property<int?>("PhimNavigationId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HinhAnh__3214EC272D4B69CB");

                    b.HasIndex("PhimNavigationId");

                    b.ToTable("HinhAnh", (string)null);
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("MaDatVe")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiamGia")
                        .HasColumnType("int");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgayXuat")
                        .HasColumnType("date");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.Property<int?>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13B5131F5A5");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.KhungGio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time");

                    b.HasKey("Id")
                        .HasName("PK__KhungGio__3214EC2782A9AD02");

                    b.ToTable("KhungGio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GioBatDau = new TimeOnly(9, 15, 0),
                            GioKetThuc = new TimeOnly(11, 45, 0)
                        },
                        new
                        {
                            Id = 2,
                            GioBatDau = new TimeOnly(12, 30, 0),
                            GioKetThuc = new TimeOnly(14, 15, 0)
                        },
                        new
                        {
                            Id = 3,
                            GioBatDau = new TimeOnly(15, 10, 0),
                            GioKetThuc = new TimeOnly(17, 25, 0)
                        },
                        new
                        {
                            Id = 4,
                            GioBatDau = new TimeOnly(18, 5, 0),
                            GioKetThuc = new TimeOnly(20, 50, 0)
                        },
                        new
                        {
                            Id = 5,
                            GioBatDau = new TimeOnly(21, 20, 0),
                            GioKetThuc = new TimeOnly(23, 35, 0)
                        },
                        new
                        {
                            Id = 6,
                            GioBatDau = new TimeOnly(0, 15, 0),
                            GioKetThuc = new TimeOnly(2, 40, 0)
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.LichChieu", b =>
                {
                    b.Property<int>("MaLichChieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichChieu"));

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("GioChieu")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayChieu")
                        .HasColumnType("date");

                    b.Property<bool?>("TinhTrang")
                        .HasColumnType("bit");

                    b.HasKey("MaLichChieu")
                        .HasName("PK__LichChie__DC740197B3AF7358");

                    b.HasIndex("GioChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhong");

                    b.ToTable("LichChieu", (string)null);

                    b.HasData(
                        new
                        {
                            MaLichChieu = 1,
                            GiaVe = 100000m,
                            GioChieu = 1,
                            MaPhim = 1,
                            MaPhong = 1,
                            NgayChieu = new DateOnly(2025, 1, 8),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 2,
                            GiaVe = 100000m,
                            GioChieu = 2,
                            MaPhim = 2,
                            MaPhong = 2,
                            NgayChieu = new DateOnly(2025, 1, 9),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 3,
                            GiaVe = 100000m,
                            GioChieu = 3,
                            MaPhim = 3,
                            MaPhong = 3,
                            NgayChieu = new DateOnly(2025, 1, 10),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 4,
                            GiaVe = 100000m,
                            GioChieu = 4,
                            MaPhim = 4,
                            MaPhong = 4,
                            NgayChieu = new DateOnly(2025, 1, 11),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 5,
                            GiaVe = 100000m,
                            GioChieu = 5,
                            MaPhim = 5,
                            MaPhong = 5,
                            NgayChieu = new DateOnly(2025, 1, 12),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 6,
                            GiaVe = 100000m,
                            GioChieu = 6,
                            MaPhim = 1,
                            MaPhong = 6,
                            NgayChieu = new DateOnly(2025, 1, 13),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 7,
                            GiaVe = 100000m,
                            GioChieu = 1,
                            MaPhim = 2,
                            MaPhong = 1,
                            NgayChieu = new DateOnly(2025, 1, 14),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 8,
                            GiaVe = 100000m,
                            GioChieu = 2,
                            MaPhim = 3,
                            MaPhong = 2,
                            NgayChieu = new DateOnly(2025, 1, 15),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 9,
                            GiaVe = 100000m,
                            GioChieu = 3,
                            MaPhim = 4,
                            MaPhong = 3,
                            NgayChieu = new DateOnly(2025, 1, 16),
                            TinhTrang = true
                        },
                        new
                        {
                            MaLichChieu = 10,
                            GiaVe = 100000m,
                            GioChieu = 4,
                            MaPhim = 5,
                            MaPhong = 4,
                            NgayChieu = new DateOnly(2025, 1, 17),
                            TinhTrang = true
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DaoDien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GioiHanDoTuoi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKhoiChieu")
                        .HasColumnType("date");

                    b.Property<int?>("SoSuatChieu")
                        .HasColumnType("int");

                    b.Property<string>("TenPhim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TheLoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Phim__3214EC27C9B2D53C");

                    b.HasIndex("TheLoai");

                    b.ToTable("Phim", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaoDien = "Director A",
                            GioiHanDoTuoi = 13,
                            MoTa = "Action-packed movie about...",
                            NgayKetThuc = new DateOnly(2024, 2, 28),
                            NgayKhoiChieu = new DateOnly(2024, 1, 15),
                            SoSuatChieu = 50,
                            TenPhim = "Action Movie 1",
                            TheLoai = "TLP001",
                            ThoiLuong = 120,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 2,
                            DaoDien = "Director B",
                            GioiHanDoTuoi = 16,
                            MoTa = "A romantic story about...",
                            NgayKetThuc = new DateOnly(2024, 3, 15),
                            NgayKhoiChieu = new DateOnly(2024, 2, 1),
                            SoSuatChieu = 40,
                            TenPhim = "Romantic Movie 1",
                            TheLoai = "TLP002",
                            ThoiLuong = 110,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 3,
                            DaoDien = "Director C",
                            GioiHanDoTuoi = 18,
                            MoTa = "A terrifying horror film...",
                            NgayKetThuc = new DateOnly(2024, 3, 31),
                            NgayKhoiChieu = new DateOnly(2024, 3, 1),
                            SoSuatChieu = 35,
                            TenPhim = "Horror Movie 1",
                            TheLoai = "TLP003",
                            ThoiLuong = 95,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 4,
                            DaoDien = "Director D",
                            GioiHanDoTuoi = 0,
                            MoTa = "An animated adventure for...",
                            NgayKetThuc = new DateOnly(2024, 4, 15),
                            NgayKhoiChieu = new DateOnly(2024, 3, 20),
                            SoSuatChieu = 15,
                            TenPhim = "Animated Movie 1",
                            TheLoai = "TLP004",
                            ThoiLuong = 90,
                            TrangThai = 1
                        },
                        new
                        {
                            Id = 5,
                            DaoDien = "Director E",
                            GioiHanDoTuoi = 13,
                            MoTa = "A sci-fi epic about...",
                            NgayKetThuc = new DateOnly(2024, 4, 30),
                            NgayKhoiChieu = new DateOnly(2024, 4, 10),
                            SoSuatChieu = 22,
                            TenPhim = "Sci-Fi Movie 1",
                            TheLoai = "TLP005",
                            ThoiLuong = 135,
                            TrangThai = 1
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Phong", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("LoaiPhong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongGhe")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Phong__3214EC27E14F6440");

                    b.ToTable("Phong", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SoLuongGhe = 112,
                            TenPhong = "Phòng 1",
                            TinhTrang = 1
                        },
                        new
                        {
                            Id = 2,
                            SoLuongGhe = 112,
                            TenPhong = "Phòng 2",
                            TinhTrang = 1
                        },
                        new
                        {
                            Id = 3,
                            SoLuongGhe = 112,
                            TenPhong = "Phòng 3",
                            TinhTrang = 1
                        },
                        new
                        {
                            Id = 4,
                            SoLuongGhe = 112,
                            TenPhong = "Phòng 4",
                            TinhTrang = 1
                        },
                        new
                        {
                            Id = 5,
                            SoLuongGhe = 112,
                            TenPhong = "Phòng 5",
                            TinhTrang = 1
                        },
                        new
                        {
                            Id = 6,
                            SoLuongGhe = 112,
                            TenPhong = "Phòng 6",
                            TinhTrang = 1
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.RefreshToken", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TokenID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("refreshtoken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("IdtaiKhoan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("IDTaiKhoan")
                        .IsFixedLength();

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("CCCD")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Hinh")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("SDT")
                        .IsFixedLength();

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .IsFixedLength();

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int?>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("IdtaiKhoan")
                        .HasName("PK__TaiKhoan__BC5F907CDEBE2E2D");

                    b.ToTable("TaiKhoan", (string)null);

                    b.HasData(
                        new
                        {
                            IdtaiKhoan = "AD001",
                            Cccd = "123456789012",
                            DiaChi = "123 Đường ABC, Thành phố XYZ",
                            DiemTichLuy = 0,
                            Email = "nguyenquangquyX@gmail.com",
                            GioiTinh = true,
                            MatKhau = "8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92",
                            NgayDangKy = new DateOnly(2025, 2, 10),
                            NgaySinh = new DateOnly(1999, 5, 19),
                            Sdt = "0973713274",
                            TenNguoiDung = "Quản trị viên",
                            TenTaiKhoan = "Admin",
                            TrangThai = 1,
                            VaiTro = 2
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.TheLoaiPhim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID");

                    b.Property<string>("TenTheLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__TheLoaiP__3214EC2721C910CA");

                    b.ToTable("TheLoaiPhim", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TLP001",
                            TenTheLoai = "Hành Động"
                        },
                        new
                        {
                            Id = "TLP002",
                            TenTheLoai = "Lãng Mạn"
                        },
                        new
                        {
                            Id = "TLP003",
                            TenTheLoai = "Kinh Dị"
                        },
                        new
                        {
                            Id = "TLP004",
                            TenTheLoai = "Hoạt Hình"
                        },
                        new
                        {
                            Id = "TLP005",
                            TenTheLoai = "Khoa Học Viễn Tưởng"
                        });
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Ve", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaGhe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.Property<int?>("MaLichChieu")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhimNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("MaVe")
                        .HasName("PK__Ve__2725100F2802FE7C");

                    b.HasIndex("MaGhe");

                    b.HasIndex("MaLichChieu");

                    b.HasIndex("MaPhimNavigationId");

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Video", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<int?>("Phim")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Video__3214EC27FC0AF659");

                    b.HasIndex("Phim");

                    b.ToTable("Video", (string)null);
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.ChiTietCombo", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Combo", "Combo")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Ghe", null)
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("GheMaGhe");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__ChiTietHo__MaHoa__5AEE82B9");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Ve", "MaVeNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaVe")
                        .HasConstraintName("FK__ChiTietHo__MaVe__59FA5E80");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaVeNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Coupon", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.GiamGia", "MaGiamGiaNavigation")
                        .WithMany("Coupons")
                        .HasForeignKey("MaGiamGia")
                        .HasConstraintName("FK__Coupon__MaGiamGi__534D60F1");

                    b.Navigation("MaGiamGiaNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.DatVe", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.TaiKhoan", "MaKhachHangNavigation")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DatVe__MaKhachHa__4D94879B");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Ve", "MaVeNavigation")
                        .WithMany()
                        .HasForeignKey("MaVe")
                        .HasConstraintName("FK__DatVe__MaVe__4E88ABD4");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaVeNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.HinhAnh", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Phim", "PhimNavigation")
                        .WithMany()
                        .HasForeignKey("PhimNavigationId");

                    b.Navigation("PhimNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Coupon", "MaGiamGiaNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaGiamGia")
                        .HasConstraintName("FK__HoaDon__MaGiamGi__571DF1D5");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.TaiKhoan", "MaKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__HoaDon__MaKhachH__5629CD9C");

                    b.Navigation("MaGiamGiaNavigation");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.LichChieu", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.KhungGio", "GioChieuNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("GioChieu")
                        .HasConstraintName("FK__LichChieu__GioCh__440B1D61");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Phim", "MaPhimNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaPhim")
                        .HasConstraintName("FK__LichChieu__MaPhi__4316F928");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Phong", "MaPhongNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK__LichChieu__MaPho__4222D4EF");

                    b.Navigation("GioChieuNavigation");

                    b.Navigation("MaPhimNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Phim", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.TheLoaiPhim", "TheLoaiNavigation")
                        .WithMany("Phims")
                        .HasForeignKey("TheLoai")
                        .HasConstraintName("FK__Phim__TheLoai__3B75D760");

                    b.Navigation("TheLoaiNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Ve", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Ghe", "MaGheNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("MaGhe")
                        .HasConstraintName("FK_Ve_Ghe");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.LichChieu", "MaLichChieuNavigation")
                        .WithMany("Ves")
                        .HasForeignKey("MaLichChieu")
                        .HasConstraintName("FK__Ve__MaLichChieu__49C3F6B7");

                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Phim", "MaPhimNavigation")
                        .WithMany()
                        .HasForeignKey("MaPhimNavigationId");

                    b.Navigation("MaGheNavigation");

                    b.Navigation("MaLichChieuNavigation");

                    b.Navigation("MaPhimNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Video", b =>
                {
                    b.HasOne("ProjectGSMAUI.Api.Data.Entities.Phim", "PhimNavigation")
                        .WithMany("Videos")
                        .HasForeignKey("Phim")
                        .HasConstraintName("FK__Video__Phim__7C4F7684");

                    b.Navigation("PhimNavigation");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Combo", b =>
                {
                    b.Navigation("ChiTietCombos");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Coupon", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Ghe", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.GiamGia", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.KhungGio", b =>
                {
                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.LichChieu", b =>
                {
                    b.Navigation("Ves");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Phim", b =>
                {
                    b.Navigation("LichChieus");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Phong", b =>
                {
                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietCombos");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.TaiKhoan", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.TheLoaiPhim", b =>
                {
                    b.Navigation("Phims");
                });

            modelBuilder.Entity("ProjectGSMAUI.Api.Data.Entities.Ve", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
